/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  // openApiSidebar: [
  //   {
  //     type: "category",
  //     label: "Petstore",
  //     link: {
  //       type: "generated-index",
  //       title: "Petstore API",
  //       description:
  //         "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
  //       slug: "/category/petstore-api",
  //     },
  //     // @ts-ignore
  //     items: require("./docs/petstore/sidebar.js"),
  //   },
  // ],
  aiMarketplaceSidebar: [
    {
      type: "category",
      label: "AI Marketplace",
      link: {
        type: "generated-index",
        title: "AI Marketplace API",
        description: "Inference API Documentation",
        slug: "/ai-marketplace",
      },
      // @ts-ignore
      items: require("./docs/ai-marketplace/sidebar.js"),
    },
  ],
  customizedAISidebar: [
    {
      type: "category",
      label: "Customized AI",
      link: {
        type: "generated-index",
        title: "Customized AI",
        description: "Customized Inference API Documentation",
        slug: "/customized-ai",
      },
      // @ts-ignore
      items: require("./docs/customized-ai/sidebar.js"),
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
